apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
   replicas: 3
   selector:
     app: myjavaapp
   tameplate:
     metadata:
       labels:
          app: myjavaapp
     spec:
        containers:
        - name: myjavaapp-container   
          image: maha4iac/mahaonlinestore:1
          ports:
          - containerPort: 8080 